spring:
  datasource:
    platform: postgres
    url: jdbc:${postgresql://postgres:1234@localhost:5432/postgres}
    username: ${POSTGRES_USER}
    password: ${atradius}
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
